CREATE TABLE `mandag24`.`teams` (`Id` SERIAL NOT NULL , `Name` TEXT NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

CREATE TABLE `mandag24`.`student` (`Id` SERIAL NOT NULL , `Name` TEXT NOT NULL , `TeamsId` BIGINT NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

ALTER TABLE `mandag24`.`student` ADD  FOREIGN KEY (`teams_id`) REFERENCES `teams`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
